import type { Metadata } from "next";
import { Inter } from "next/font/google";

import NextAuthWrapper from "@/library/nextauth.provider";

const inter = Inter({ subsets: ["latin"] });
import "./globals.css";

import "primereact/resources/themes/lara-light-cyan/theme.css";

import "primeicons/primeicons.css";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <NextAuthWrapper>{children}</NextAuthWrapper>
      </body>
    </html>
  );
}
