import type { Metadata } from "next";
import { Inter } from "next/font/google";
import NextAuthWrapper from "@/library/nextauth.provider";
import ThemeProvider from "@/library/ThemeProvider";
import { notFound } from "next/navigation";
const inter = Inter({ subsets: ["latin"] });
import "./globals.css";
import "primereact/resources/themes/lara-light-cyan/theme.css";
import "primeicons/primeicons.css";
import Themefull from "@/components/Theme/Theme";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const supportedLocales = ["en", "de"];

// Root layout component
export default function RootLayout({
  children,
  params,
}: {
  children: React.ReactNode;
  params: { [key: string]: any };
}) {
  // Extract the current locale from the params
  let currentLocale = params.locale || "en";

  // Ensure the current locale is supported
  if (!supportedLocales.includes(currentLocale)) {
    currentLocale = "en";
  }
  return (
    <html lang={currentLocale}>
      <body className={inter.className}>
        <NextAuthWrapper>
          <ThemeProvider>
            <Themefull>{children}</Themefull>
          </ThemeProvider>
        </NextAuthWrapper>
      </body>
    </html>
  );
}
